## Feature Engineering  
### Feature Selection  
Selection of `Features` which contribute most to the prediction variable  
Develop an Intuition towards some features that are needed to solve the problem and remove unnecessary features.  
Techniques for the FE
1. Correlation of features with target variable  
df.corr()['y_feature'].sort_values().plot.branch() (`Based on +/- correlation`)  
df.corr()['y_feature'].abs().sort_values().plot.branch() (`Based on True correlation`)
This is pearson correlation and this applicable only to numerical features  
  
2. Methods for plotting feature importance.  
** Correlation as described in `point-1`  
** Feature importance of some models when we train them.  
1.Linear models(`model.coef_`) 2.XGBoost 3.LightGBM 4.Random Forest(model.feature_importances_)  
** Permutation feature importance for every ML model.  
`from sklearn.inspection import permutation_importance`  
** SHAP- Individual feature importance.  
  
3. Automatic feature selection.  
There are lots of them, most important them of are  
`Variance Threshold` and `select KBest.`  

#### Types of correlation according to variables.
<img src="types_of_correlation.PNG"
     alt="Markdown Monster icon"
     style="float: left; margin-right: 10px;" />

In [6]:
import pandas as pd
import numpy as np

In [5]:
# feature generation. We have give kms travelled in particular time 
#but relation between time and distance is missing 
# So, we add a feature by using the distance and time features.
# speed = distance/time
df = pd.DataFrame({'km':[1,2,3,4],'hours':[1,1,2,1]})
df['mean speed'] = df.apply(lambda row:  row['km']/row['hours'], axis=1)
df

   km  hours  mean speed
0   1      1         1.0
1   2      1         2.0
2   3      2         1.5
3   4      1         4.0

In [11]:
# generation of Data.
# This technique will become handy, when we have very little data
df_new = df.copy()
df_new[['km','hours']] = df_new.apply(lambda row: row[['km','hours']]+np.random.random_sample()*0.1, axis=1 )
# we need to append our random data to our origin df
df = df.append(df_new.sample(int(df_new.shape[0]/4)))
df

         km     hours  mean speed
0  1.000000  1.000000         1.0
1  2.000000  1.000000         2.0
2  3.000000  2.000000         1.5
3  4.000000  1.000000         4.0
2  3.091136  2.091136         1.5
2  3.138103  2.138103         1.5
2  3.093497  2.093497         1.5
2  3.049591  2.049591         1.5